version: '3.10.2'
services:

  web:
    container_name: "web"
    image: nginx:alphine
    depends_on:
      - app
    ports:
      - "8082:80"
    volumes:
      - ./api/conf.d:/etc/nginx/conf.d
    networks:
      - custom

  app:
    container_name: "app"
    image: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - custom

networks:
  custom:
    driver: bridge